#!/bin/bash
#
# Author: paraxic
# Version: 0.10 
# Date: 02/04/2017
#
# Desc: panel-info for lemonbar

bg_color="%{B#"
fg_color="%{F#"
#deco colors
deco_red="FB2014}"
deco_black="141314}"
deco_white="FFFFFD}"
deco_blue="040F2D}"
deco_orange="FB3F04}"
deco_purple="3C2637}"
deco_green="859B47}"

#stat vars

function battery(){
	stat /usr/bin/acpi &> /dev/null
	if [[ $? != 0 ]]
	then
		echo "ACPI client missing! ( sudo pacman -Syu acpi )" 1 > 2
	else
	BATSTAT=$(acpi | awk -F " " '{print $3}' | sed s/,//)
	BATPERCENT=$(acpi | awk -F " " '{print $4}' | sed s/,//)
	  if [[ $BATSTAT = "Charging" ]]
	  then
		BATSTAT='C'
	  elif [[ $BATSTAT = 'Discharging' ]]
	  then
		BATSTAT='D'
	  fi
		echo -n " Bat[$BATSTAT]: $BATPERCENT"
	fi
}

function color_reset() {
	echo -n "%{F-}%{B-}"
}

function clock() {
	TIME=$(date +"%I:%M %p" | awk '{print toupper($0)}')
	DATE=$(date +"%D")
	echo -n " $DATE "
	echo " $TIME "
	#color_reset
}

# Panel Loop
while true; do
#	echo -n "%{l}"
	echo -n "$(battery)"
	echo -n "$(clock)"
	sleep 1
	echo
done
